"use client";
import { useEffect, useRef, useState } from "react";
type Region={regionId:string;regionName:string;isDemo:boolean;lastUpdated:string}; type Result=any;
const sampleLabels:Record<string,string>={pet:"투명 페트병",container:"오염된 배달용기",battery:"폐건전지",unknown:"인식 불가능한 물체"};
export default function Home() {
 const [regions,setRegions]=useState<Region[]>([]),[region,setRegion]=useState("sample-seoul"),[file,setFile]=useState<File|null>(null),[preview,setPreview]=useState(""),[sample,setSample]=useState("pet"),[loading,setLoading]=useState(false),[result,setResult]=useState<Result|null>(null),[error,setError]=useState(""),[feedback,setFeedback]=useState(""),[history,setHistory]=useState<{name:string;at:string}[]>([]); const input=useRef<HTMLInputElement>(null);
 useEffect(()=>{fetch("/api/regions").then(r=>r.json()).then(setRegions).catch(()=>setError("지역 목록을 불러오지 못했습니다."));try{setHistory(JSON.parse(localStorage.getItem("recycle-history")||"[]"))}catch{}},[]);
 const choose=(f:File|null)=>{setError("");setResult(null);if(!f)return;if(!f.type.startsWith("image/")){setError("이미지 파일만 선택할 수 있습니다.");return}if(f.size>10*1024*1024){setError("이미지는 10MB 이하만 가능합니다.");return}setFile(f);setPreview(URL.createObjectURL(f));setSample("");};
 const analyze=async()=>{if(!file){setError("사진을 선택하거나 데모 항목을 골라 주세요.");return}setLoading(true);setError("");try{const form=new FormData();form.append("image",file);form.append("regionId",region);if(sample)form.append("sample",sample);const r=await fetch("/api/analyze",{method:"POST",body:form});const data=await r.json();if(!r.ok)throw new Error(data.error);setResult(data);const next=[{name:data.detectedItems?.[0]?.name,at:new Date().toLocaleString("ko-KR")},...history].slice(0,3);setHistory(next);localStorage.setItem("recycle-history",JSON.stringify(next));}catch(e){setError(e instanceof Error?e.message:"분석에 실패했습니다.")}finally{setLoading(false)}};
 const sendFeedback=async(rating:string)=>{if(!result)return;const res=await fetch("/api/feedback",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({analysisId:result.analysisId,rating})});setFeedback(res.ok?"소중한 의견을 저장했습니다.":"의견 저장에 실패했습니다.")};
 const reset=()=>{setResult(null);setFile(null);setPreview("");setSample("pet");setFeedback("")};
 if(result) { const item=result.detectedItems[0]; return <main className="shell result"><header><span className="tag">{result.mode === "demo" ? "데모 분석" : "AI 분석"}</span><h1>분석 결과</h1><p className="muted">AI 판별과 지역 규칙을 분리해 안내합니다.</p></header>{result.warnings?.map((w:string)=><p className="warn" key={w}>⚠️ {w}</p>)}<section className="card"><h2>{item.name}</h2><div className="grid"><Info title="재질" value={item.material.join(", ")||"확인 필요"}/><Info title="재활용 여부" value={status(item.recyclableStatus)}/><Info title="판별 신뢰도" value={`${Math.round(item.confidence*100)}% · ${confidence(item.confidence)}`}/><Info title="오염 상태" value={`${item.contamination.status} · ${item.contamination.description}`}/></div><h3>분리할 부속품</h3>{item.components.length?<ul>{item.components.map((c:any)=><li key={c.name}><b>{c.name}</b> ({c.material}): {c.action}</li>)}</ul>:<p>별도 부속품이 확인되지 않았습니다.</p>}<h3>지역별 배출 안내</h3><p className="tag">시연용 규칙 · {result.region.regionName}</p>{result.disposalGuides.map((g:any)=><div key={g.itemName}><p><b>{g.collectionType}</b></p><ol>{g.steps.map((s:string)=><li key={s}>{s}</li>)}</ol></div>)}<h3>판별 근거</h3><ul>{item.evidence.length?item.evidence.map((e:string)=><li key={e}>{e}</li>):<li>사진에서 충분한 근거를 찾지 못했습니다.</li>}</ul>{item.uncertainties.length>0&&<><h3>확인이 필요한 점</h3><ul>{item.uncertainties.map((u:string)=><li key={u}>{u}</li>)}</ul></>}<p className="muted">정보 출처: {result.region.sourceName} · 기준일: {result.region.lastUpdated} · 영구적으로 사진을 저장하지 않습니다.</p></section>{result.needsMoreInformation&&<section className="card" style={{marginTop:14}}><h2>추가 확인이 필요해요</h2><ul>{result.followUpQuestions.map((q:string)=><li key={q}>{q}</li>)}</ul><button className="btn btn-alt" onClick={reset}>다시 촬영하기</button></section>}<section className="card" style={{marginTop:14}}><h2>결과가 맞나요?</h2><div className="grid"><button className="sample" onClick={()=>sendFeedback("correct")}>👍 맞아요</button><button className="sample" onClick={()=>sendFeedback("incorrect")}>👎 틀려요</button><button className="sample" onClick={()=>sendFeedback("unknown")}>🤷 잘 모르겠어요</button></div>{feedback&&<p role="status">{feedback}</p>}<button className="btn" style={{marginTop:14}} onClick={reset}>새 사진으로 판별하기</button></section></main>}
 return <main className="shell"><header><span className="tag">사진은 분석 후 저장하지 않아요</span><h1 style={{fontSize:32,marginBottom:8}}>바로버려 ♻️</h1><p className="muted">사진 한 장으로 알아보는 쉬운 분리배출 안내</p></header><section className="card"><label className="label" htmlFor="region">거주 지역 선택</label><select id="region" value={region} onChange={e=>setRegion(e.target.value)}>{regions.map(r=><option key={r.regionId} value={r.regionId}>{r.regionName} · 시연용 규칙</option>)}</select><h2>데모로 먼저 확인하기</h2><div className="grid">{Object.entries(sampleLabels).map(([key,label])=><button key={key} className="sample" aria-pressed={sample===key} onClick={()=>{setSample(key);setFile(new File(["demo"],`${key}.png`,{type:"image/png"}));setPreview("")}}>{label}</button>)}</div><p className="muted">또는 내 사진을 선택하세요. 개인정보가 포함된 사진은 올리지 마세요.</p><div className="drop" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();choose(e.dataTransfer.files[0])}}><input ref={input} hidden type="file" accept="image/*" capture="environment" onChange={e=>choose(e.target.files?.[0]||null)}/><button className="btn btn-alt" onClick={()=>input.current?.click()}>카메라 촬영 또는 사진 선택</button><p>사진을 여기로 끌어다 놓아도 됩니다.</p></div>{preview&&<><img className="preview" src={preview} alt="선택한 사진 미리보기"/><button className="btn btn-alt" style={{marginTop:10}} onClick={reset}>사진 삭제</button></>}{error&&<p className="warn" role="alert">{error}</p>}<button className="btn" style={{marginTop:18}} disabled={loading} onClick={analyze}>{loading?"물체 종류 · 재질 · 지역 기준을 확인 중…":"사진으로 판별하기"}</button></section>{history.length>0&&<section className="card" style={{marginTop:14}}><h2>최근 판별 기록</h2><ul>{history.map((h,i)=><li key={`${h.at}-${i}`}><b>{h.name}</b> · {h.at}</li>)}</ul></section>}<p className="muted">AI 결과는 참고용입니다. 위험 물질·의료폐기물·폭발 위험 물질은 전문기관 또는 관할 기관에 먼저 확인하세요.</p></main>;
}
function Info({title,value}:{title:string;value:string}){return <div><b>{title}</b><p className="muted">{value}</p></div>} function confidence(n:number){return n>=.8?"높음":n>=.5?"보통":"낮음"} function status(s:string){return ({RECYCLABLE:"재활용 가능",CONDITIONAL:"조건부 가능",NON_RECYCLABLE:"재활용 어려움",SPECIAL_COLLECTION:"별도 수거",UNKNOWN:"확인 필요"} as Record<string,string>)[s]||s}
