"use client";
import { useEffect, useMemo, useRef, useState } from "react";
import { nearestSupportedRegion } from "@/lib/location";
type Region={regionId:string;regionName:string;group:string}; type Result=any;
const samples:Record<string,string>={pet:"투명 페트병",container:"오염된 배달용기",battery:"폐건전지",unknown:"인식 불가능한 물체"};
export default function Home(){
 const [regions,setRegions]=useState<Region[]>([]),[region,setRegion]=useState("seoul-gangnam"),[residence,setResidence]=useState("아파트"),[file,setFile]=useState<File|null>(null),[sample,setSample]=useState("pet"),[preview,setPreview]=useState(""),[result,setResult]=useState<Result|null>(null),[previous,setPrevious]=useState<Result|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState(""),[locationNote,setLocationNote]=useState(""); const input=useRef<HTMLInputElement>(null);
 const selected=regions.find(r=>r.regionId===region); const groups=useMemo(()=>regions.reduce<Record<string,Region[]>>((all,r)=>{(all[r.group]??=[]).push(r);return all},{}),[regions]);
 useEffect(()=>{fetch("/api/regions").then(r=>r.json()).then(setRegions).catch(()=>setError("지역 목록을 불러오지 못했습니다."));},[]);
 const choose=(next:File|null)=>{setError("");if(!next)return;if(!next.type.startsWith("image/"))return setError("이미지 파일만 선택할 수 있습니다.");if(next.size>30*1024*1024)return setError("이미지는 30MB 이하만 가능합니다.");setFile(next);setSample("");setPreview(URL.createObjectURL(next));};
 const sampleChoose=(key:string)=>{setSample(key);setFile(new File(["demo"],`${key}.png`,{type:"image/png"}));setPreview("");};
 const autoRegion=()=>{if(!navigator.geolocation)return setLocationNote("이 브라우저는 위치 기능을 지원하지 않습니다.");setLocationNote("현재 위치로 가까운 지원 지역을 찾는 중입니다…");navigator.geolocation.getCurrentPosition(({coords})=>{const near=nearestSupportedRegion(coords.latitude,coords.longitude);const found=regions.find(r=>r.regionId===near.regionId);if(found){setRegion(found.regionId);setLocationNote(`${found.regionName}을(를) 가까운 지원 지역으로 제안했습니다. 정확한 구는 직접 확인해 주세요.`)}},()=>setLocationNote("위치 권한이 필요합니다. 직접 지역을 선택해 주세요."),{enableHighAccuracy:false,timeout:8000,maximumAge:300000});};
 const analyze=async()=>{if(!file)return setError("사진을 선택해 주세요.");setLoading(true);setError("");try{const form=new FormData();form.append("image",file);form.append("regionId",region);form.append("residenceType",residence);if(sample)form.append("sample",sample);if(previous)form.append("previousSummary",previous.detectedItems.map((i:any)=>`${i.name}(${i.material.join(",")})`).join(", "));const res=await fetch("/api/analyze",{method:"POST",body:form});const data=await res.json();if(!res.ok)throw new Error(data.error);setResult(data);setPrevious(null);}catch(e){setError(e instanceof Error?e.message:"분석에 실패했습니다.");}finally{setLoading(false)}};
 if(result)return <ResultView result={result} residence={residence} onReanalyze={()=>{setPrevious(result);setResult(null);setFile(null);setSample("");setPreview("");}} onReset={()=>{setResult(null);setPrevious(null);setFile(null);setPreview("");setSample("pet")}} />;
 return <main className="shell"><header><span className="tag">사진은 분석 후 저장하지 않아요</span><h1>바로버려 ♻️</h1><p className="muted">사진 속 여러 물체를 나누어 분석하고 지역 기준을 안내합니다.</p></header><section className="card"><h2>1. 지역과 주거 형태</h2><label className="label" htmlFor="region">거주 지역</label><select id="region" value={region} onChange={e=>setRegion(e.target.value)}>{Object.entries(groups).map(([group,items])=><optgroup key={group} label={group}>{items.map(item=><option key={item.regionId} value={item.regionId}>{item.regionName}</option>)}</optgroup>)}</select><button className="text-button" onClick={autoRegion}>📍 현재 위치로 지역 제안</button>{locationNote&&<p className="muted" role="status">{locationNote}</p>}<label className="label" htmlFor="residence">주거 형태</label><select id="residence" value={residence} onChange={e=>setResidence(e.target.value)}><option>아파트</option><option>단독·연립·빌라</option><option>상가</option></select><h2>2. 사진 선택</h2><div className="grid">{Object.entries(samples).map(([key,label])=><button key={key} className="sample" aria-pressed={sample===key} onClick={()=>sampleChoose(key)}>{label}</button>)}</div><div className="drop"><input ref={input} hidden type="file" accept="image/*" capture="environment" onChange={e=>choose(e.target.files?.[0]??null)}/><button className="btn btn-alt" onClick={()=>input.current?.click()}>카메라 촬영 또는 사진 선택</button><p>재질 표시·옆면·전체 형태가 보이게 촬영하면 더 정확합니다.</p></div>{preview&&<img className="preview" src={preview} alt="선택한 사진 미리보기"/>}{error&&<p className="warn" role="alert">{error}</p>}<button className="btn" disabled={loading} onClick={()=>analyze()}>{loading?"여러 물체와 재질을 분석 중…":"사진으로 판별하기"}</button></section></main>;
}
function ResultView({result,residence,onReanalyze,onReset}:{result:Result;residence:string;onReanalyze:()=>void;onReset:()=>void}){const [points,setPoints]=useState<any[]>([]),[feedback,setFeedback]=useState("");useEffect(()=>{fetch(`/api/collection-points?regionId=${result.region.regionId}`).then(r=>r.json()).then(setPoints).catch(()=>{});},[result.region.regionId]);const feedbackSend=async(rating:string)=>{const r=await fetch("/api/feedback",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({analysisId:result.analysisId,rating})});setFeedback(r.ok?"의견을 저장했습니다.":"의견 저장에 실패했습니다.")};return <main className="shell result"><span className="tag">{result.detectedItems.length}개 물체 분석</span><h1>분석 결과</h1><p className="muted">{result.region.regionName} · {residence} 기준</p>{result.warnings?.map((w:string)=><p className="warn" key={w}>⚠️ {w}</p>)}{result.detectedItems.map((item:any,index:number)=>{const guide=result.disposalGuides.find((g:any)=>g.itemName===item.name);return <section className="card item-card" key={`${item.name}-${index}`}><span className="item-number">물체 {index+1}</span><h2>{item.name}</h2><div className="grid"><Info title="재질" value={item.material.join(", ")||"확인 필요"}/><Info title="재활용 여부" value={status(item.recyclableStatus)}/><Info title="신뢰도" value={`${Math.round(item.confidence*100)}% · ${confidence(item.confidence)}`}/><Info title="오염" value={item.contamination.description}/></div>{item.components.length>0&&<><h3>분리할 부속품</h3><ul>{item.components.map((c:any)=><li key={c.name}><b>{c.name}</b>: {c.action}</li>)}</ul></>}{guide&&<><h3>배출 방법</h3><p><b>{guide.collectionType}</b></p><ol>{guide.steps.map((s:string)=><li key={s}>{s}</li>)}</ol></>}{item.evidence.length>0&&<><h3>판별 근거</h3><ul>{item.evidence.map((e:string)=><li key={e}>{e}</li>)}</ul></>}{item.uncertainties.length>0&&<p className="warn">확인이 필요한 점: {item.uncertainties.join(" · ")}</p>}</section>})}{result.needsMoreInformation&&<section className="card"><h2>추가 사진으로 재분석</h2><p>재질 표시 확대, 옆면, 크기 비교 사진을 촬영해 다시 올려 주세요.</p><ul>{result.followUpQuestions.map((q:string)=><li key={q}>{q}</li>)}</ul><button className="btn btn-alt" onClick={onReanalyze}>추가 사진 촬영하기</button></section>}{points.length>0&&<section className="card"><h2>가까운 별도수거 지점</h2>{points.map(p=><p key={p.name}><b>{p.name}</b><br/>{p.address} · {p.items.join(", ")}<br/><a href={p.sourceUrl} target="_blank" rel="noreferrer">공식 출처 확인</a></p>)}</section>}<section className="card"><h2>결과가 맞나요?</h2><div className="grid"><button className="sample" onClick={()=>feedbackSend("correct")}>👍 맞아요</button><button className="sample" onClick={()=>feedbackSend("incorrect")}>👎 틀려요</button><button className="sample" onClick={()=>feedbackSend("unknown")}>🤷 잘 모르겠어요</button></div>{feedback&&<p role="status">{feedback}</p>}<button className="btn" onClick={onReset}>새 사진으로 판별하기</button></section></main>}
function Info({title,value}:{title:string;value:string}){return <div><b>{title}</b><p className="muted">{value}</p></div>}function confidence(n:number){return n>=.8?"높음":n>=.5?"보통":"낮음"}function status(s:string){return ({RECYCLABLE:"재활용 가능",CONDITIONAL:"조건부 가능",NON_RECYCLABLE:"재활용 어려움",SPECIAL_COLLECTION:"별도 수거",UNKNOWN:"확인 필요"} as Record<string,string>)[s]??s}
